/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdint.h>
#include "stm32f4xx.h"
#include "Uart.h"

char key;
int __io_putchar(int ch)
{
	uart_write(ch);
	return ch;
}

int main(void)
{


	uart_int(14400);
	GPIOA->MODER |=(1U<<10);
	GPIOA->MODER &=~(1U<<11);

	while(1)
	{
		key = uart_read();
		if(key=='1')
		{

		GPIOA->ODR ^= (1U<<5);

		}
		else
			{
		GPIOA->ODR &=~ (1U<<5);

		}



	//	for(int i=0 ; i<1000000;i++);

	}
}
