/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "Systick.h"
#include "Uart.h"

#define  GPIOAEN 		(1U<<0)



int main(void)
{
	RCC->AHB1ENR |= GPIOAEN;
	uart_int(9600);
	GPIOA->MODER |=(1U<<10);
	GPIOA->MODER &=~(1U<<11);



	while(1)
	{

		printf("Passou 1 segundo \n");
		GPIOA->ODR ^= (1U<<5);
		sys_delay_ms(1000);

	}
}
