/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "tim.h"
#include "Systick.h"
#include "Uart.h"

#define SR_IUF		(1U<<0)

int main(void)
{
	RCC->AHB1ENR |=(1U<<0);
	GPIOA->MODER |=(1U<<10);
	GPIOA->MODER &=~(1U<<11);

	uart_int(9600);
	tim_init_interrupt();
    /* Loop forever */
	while(1)
	{

	}
}


void TIM2_IRQHandler()
{
	TIM2->SR &=~SR_IUF;
	printf("A second has passed\n\r");
	GPIOA->ODR ^= (1U<<5);
}
